export const inputAll = {
  student: [
    {
      id: 101,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 1011,
          type: "number",
          field: "rollN",
          name: "Roll No",
          val: "",
          ico: "fa-id-card",
        },
        {
          id: 1012,
          type: "number",
          field: "sprNo",
          name: "SPR No",
          val: "",
          ico: "fa-id-card",
        },
        {
          id: 1013,
          type: "text",
          field: "fName",
          name: "Full Name",
          val: "",
          ico: "fa-user-circle",
        },
        {
          id: 1014,
          type: "text",
          field: "sName",
          name: "Nick Name",
          val: "",
          ico: "fa-tags",
        },

        {
          id: 1016,
          type: "date",
          field: "doBir",
          name: "DOB ",
          val: "",
          ico: "",
        },
        {
          id: 1016,
          type: "date",
          field: "doAnn",
          name: "Anniversary  ",
          val: "",
          ico: "",
        },
      ],
    },
    {
      id: 102,
      name: "Contact Info",
      tab: "contact",
      list: [
        {
          id: 1021,
          type: "text",
          field: "cuLoc",
          name: "Located In",
          val: "",
          ico: "fa-map-marker",
        },
        {
          id: 1022,
          type: "text",
          field: "naLoc",
          name: "Native Town",
          val: "",
          ico: "fa-thumb-tack",
        },

        {
          id: 1023,
          type: "email",
          field: "email",
          name: "Email Address",
          val: "",
          ico: "fa-envelope",
        },
        {
          id: 1024,
          type: "number",
          field: "mobile",
          name: "Phone No.",
          val: "",
          ico: "fa-phone-square",
        },
        {
          id: 1025,
          type: "text",
          field: "workin",
          name: "Working In",
          val: "",
          ico: "fa-business",
        },
      ],
    },
    {
      id: 103,
      name: "Social",
      tab: "social",
      list: [
        {
          id: 1031,
          type: "text",
          field: "faceB",
          name: "Facebook",
          val: "",
          ico: "fa-facebook-official",
        },
        {
          id: 1032,
          type: "text",
          field: "instA",
          name: "Instagram",
          val: "",
          ico: " fa-instagram",
        },

        {
          id: 1033,
          type: "text",
          field: "linkE",
          name: "Linked In",
          val: "",
          ico: "fa-linkedin",
        },
        {
          id: 1034,
          type: "text",
          field: "twitT",
          name: "Twitter",
          val: "",
          ico: "fa-twitter",
        },
        {
          id: 1035,
          type: "text",
          field: "blogW",
          name: "Website/ Blog",
          val: "",
          ico: "fa fa-globe",
        },
        {
          id: 1035,
          type: "text",
          field: "blogW",
          name: "Website/ Blog",
          val: "",
          ico: "fa fa-globe",
        },
      ],
    },

    {
      id: 104,
      name: "Photo",
      tab: "pic",
      list: [],
    },
  ],
  staff: [
    {
      id: 101,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 1011,
          type: "number",
          field: "rollN",
          name: "Roll No",
          val: "",
          ico: "fa-id-card",
        },

        {
          id: 1012,
          type: "text",
          field: "fName",
          name: "Full Name",
          val: "",
          ico: "fa-user-circle",
        },
        {
          id: 1013,
          type: "text",
          field: "sName",
          name: "Nick Name",
          val: "",
          ico: "fa-tags",
        },
        {
          id: 1014,
          type: "text",
          field: "wTitle",
          name: "Title No",
          val: "",
          ico: "fa-id-card",
        },

        {
          id: 1016,
          type: "date",
          field: "doBir",
          name: "DOB ",
          val: "",
          ico: "",
        },
        {
          id: 1016,
          type: "date",
          field: "doAnn",
          name: "Anniversary  ",
          val: "",
          ico: "",
        },
      ],
    },
    {
      id: 102,
      name: "Contact Info",
      tab: "contact",
      list: [
        {
          id: 1021,
          type: "text",
          field: "cuLoc",
          name: "Located In",
          val: "",
          ico: "fa-map-marker",
        },
        {
          id: 1022,
          type: "text",
          field: "naLoc",
          name: "Native Town",
          val: "",
          ico: "fa-thumb-tack",
        },

        {
          id: 1023,
          type: "email",
          field: "email",
          name: "Email Address",
          val: "",
          ico: "fa-envelope",
        },
        {
          id: 1024,
          type: "number",
          field: "mobile",
          name: "Phone No.",
          val: "",
          ico: "fa-phone-square",
        },
        {
          id: 1025,
          type: "text",
          field: "workin",
          name: "Working In",
          val: "",
          ico: "fa-business",
        },
      ],
    },
    {
      id: 103,
      name: "Social",
      tab: "social",
      list: [
        {
          id: 1031,
          type: "text",
          field: "faceB",
          name: "Facebook",
          val: "",
          ico: "fa-facebook-official",
        },
        {
          id: 1032,
          type: "text",
          field: "instA",
          name: "Instagram",
          val: "",
          ico: " fa-instagram",
        },

        {
          id: 1033,
          type: "text",
          field: "linkE",
          name: "Linked In",
          val: "",
          ico: "fa-linkedin",
        },
        {
          id: 1034,
          type: "text",
          field: "twitT",
          name: "Twitter",
          val: "",
          ico: "fa-twitter",
        },
        {
          id: 1035,
          type: "text",
          field: "blogW",
          name: "Website/ Blog",
          val: "",
          ico: "fa fa-globe",
        },
        {
          id: 1035,
          type: "text",
          field: "blogW",
          name: "Website/ Blog",
          val: "",
          ico: "fa fa-globe",
        },
      ],
    },
    {
      id: 104,
      name: "Subjects",
      tab: "subjects",
      list: [
        {
          id: 1031,
          name: "Semester 1",
          type: "text",
          val: "",
        },
        {
          id: 1032,
          name: "Semester 2",
          type: "text",
          val: "",
        },

        {
          id: 1033,
          name: "Semester 3",
          type: "text",
          val: "",
        },
        {
          id: 1034,
          name: "Semester 4",
          type: "text",
          val: "",
        },
        {
          id: 1035,
          name: "Semester 5",
          type: "text",
          val: "",
        },
        {
          id: 1035,
          name: "Semester 6",
          type: "text",
          val: "",
        },
        {
          id: 1035,
          name: "Semester 7",
          type: "text",
          val: "",
        },
        {
          id: 1035,
          name: "Semester 8",
          type: "text",
          val: "",
        },
      ],
    },
    {
      id: 105,
      name: "Photo",
      tab: "pic",
      list: [],
    },
  ],
  pages: [
    {
      id: 2001,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 20011,
          type: "text",
          field: "title",
          name: "Title",
          val: "",
        },
        {
          id: 20012,
          type: "text",
          field: "slug",
          name: "Slug",
          val: "",
        },
        {
          id: 20014,
          type: "textarea",
          field: "desC",
          name: "Description",
          val: "",
        },
      ],
    },
    {
      id: 2002,
      name: "Content",
      tab: "content",
      list: [],
    },

    {
      id: 2004,
      name: "Photo",
      tab: "pic",
      list: [],
    },
  ],
  Articles: [
    {
      id: 3001,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 30011,
          type: "text",
          field: "title",
          name: "Title",
          val: "",
        },
        {
          id: 30012,
          type: "text",
          field: "slug",
          name: "Slug",
          val: "",
        },
        {
          id: 30014,
          type: "textarea",
          field: "desC",
          name: "Description",
          val: "",
        },
      ],
    },

    {
      id: 3004,
      name: "Photo",
      tab: "pic",
      list: [],
    },
  ],
  Semester: [
    {
      id: 5001,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 50011,
          type: "text",
          field: "sName",
          name: "Title",
          val: "",
        },

        {
          id: 50012,
          type: "text",
          field: "sCord",
          name: "Coordinator",
          val: "",
        },
        {
          id: 50014,
          type: "textarea",
          field: "sDesc",
          name: "Description",
          val: "",
        },
      ],
    },
    {
      id: 5002,
      name: "Subjects",
      tab: "subjects",
      list: [],
    },
  ],
  Subjects: [
    {
      id: 5001,
      name: "Basic Info",
      tab: "basic",
      list: [
        {
          id: 50011,
          type: "text",
          field: "sName",
          name: "Name",
          val: "",
        },
        {
          id: 50012,
          type: "text",
          field: "sCode",
          name: "Code",
          val: "",
        },
        {
          id: 50014,
          type: "textarea",
          field: "sDesc",
          name: "Description",
          val: "",
        },
        {
          id: 50012,
          type: "text",
          field: "sTaff",
          name: "Facalty",
          val: "",
        },
      ],
    },
  ],
};
